# Generated by Django 4.2.7 on 2024-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlockk', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
