# Generated by Django 5.0.3 on 2024-06-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlockk', '0009_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
