# Generated by Django 3.2.25 on 2024-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockk', '0011_auto_20240618_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
